/*	IBM S/36 MACHINE SPECIFIC LIMITS
 *	copyright (c) 1985, 1986 by Whitesmiths, Ltd.
 */

#ifndef __M36__
#define __M36__		1

/*	S/36 dependent
 */
#define _CBIT		8
#define _CMAX		256
#define _CMIN		0
#define _DDIG		15
#define _DMAXEX		76
#define _DMINEX		-76
#define _DRAD		2
#define _DROUND		0
#define _FDIG		6
#define _FMAXEX		76
#define _FMINEX		-76
#define _FRAD		2
#define _FROUND		0
#define _IMAX		32767
#define _IMIN		-32768
#define _JMPSIZ		4
#define _LDDIG		15
#define _LDMAXEX	76
#define _LDMINEX	-76
#define _LDRAD		2
#define _LDROUND	0
#define _LMAX		2147483647
#define _LMIN		-2147483648	
#define _SCMAX		127
#define _SCMIN		-127
#define _SMAX		32767
#define _SMIN		-32768
#define _UCMAX		255
#define _UIMAX		65535
#define _ULMAX		4294967295
#define _USMAX		65535

#endif
