type b:cright
pip a:=b:libu.80
era b:libu.80
pip a:=b:*.h
era b:*.h
pip a:=b:*.sub
era b:c.sub
era b:ld.sub
era b:test.sub
era a:buildc.sub
pip a:=b:echo.c
era b:echo.*
era b:cright
pip a:=b:instal.doc
era b:instal.doc
link -eb__memory -ed__edata -tb0x100 -htro b:as80.com crts.80 b:as.o libc.80
era b:as.o
link -eb__memory -ed__edata -tb0x100 -htro b:pp.com crts.80 b:p0.o libc.80
era b:p0.o
link -eb__memory -ed__edata -tb0x100 -htro b:p1.com crts.80 b:p1.o libc.80
era b:p1.o
link -eb__memory -ed__edata -tb0x100 -htro b:p280.com crts.80 b:p2.o libc.80
era b:p2.o
era b:buildc.sub
